"""Inicial

Revision ID: 24a048bf6f70
Revises: 
Create Date: 2024-09-30 17:08:38.382136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a048bf6f70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_autores_id'), 'autores', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    op.create_table('tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tecnicas_id'), 'tecnicas', ['id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('continente', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'usuario', name='rolenum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('suscrito', sa.Boolean(), nullable=True),
    sa.Column('fecha_suscripcion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletters_id'), 'newsletters', ['id'], unique=False)
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('palabras_clave', sa.Text(), nullable=True),
    sa.Column('url_imagen', sa.String(length=255), nullable=True),
    sa.Column('adicionales', sa.JSON(), nullable=True),
    sa.Column('tipo_obra', sa.Enum('pintura', 'publicacion', 'multimedia', name='tipoenum'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_id'), 'obras', ['id'], unique=False)
    op.create_table('detalles_obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('tecnica', sa.String(length=255), nullable=True),
    sa.Column('estado_conservacion', sa.String(length=255), nullable=True),
    sa.Column('dimensiones', sa.String(length=255), nullable=True),
    sa.Column('movimiento', sa.String(length=255), nullable=True),
    sa.Column('editor', sa.String(length=255), nullable=True),
    sa.Column('lugar_publicacion', sa.String(length=255), nullable=True),
    sa.Column('generos', sa.String(length=255), nullable=True),
    sa.Column('idioma', sa.String(length=50), nullable=True),
    sa.Column('numero_paginas', sa.Integer(), nullable=True),
    sa.Column('tipo_multimedia', sa.String(length=255), nullable=True),
    sa.Column('duracion', sa.String(length=255), nullable=True),
    sa.Column('formato', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obra_id')
    )
    op.create_index(op.f('ix_detalles_obras_id'), 'detalles_obras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_obras_id'), table_name='detalles_obras')
    op.drop_table('detalles_obras')
    op.drop_index(op.f('ix_obras_id'), table_name='obras')
    op.drop_table('obras')
    op.drop_index(op.f('ix_newsletters_id'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_tecnicas_id'), table_name='tecnicas')
    op.drop_table('tecnicas')
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_autores_id'), table_name='autores')
    op.drop_table('autores')
    # ### end Alembic commands ###
