"""Modificacion Pintura

Revision ID: 51438c49aa68
Revises: 7f5ec6ababea
Create Date: 2024-08-15 23:19:08.677185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51438c49aa68'
down_revision: Union[str, None] = '7f5ec6ababea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinturas', sa.Column('tecnica_id', sa.Integer(), nullable=True))
    op.add_column('pinturas', sa.Column('movimiento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pinturas', 'tecnicas', ['tecnica_id'], ['id'])
    op.create_foreign_key(None, 'pinturas', 'movimientos', ['movimiento_id'], ['id'])
    op.drop_column('pinturas', 'movimiento')
    op.drop_column('pinturas', 'tecnica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinturas', sa.Column('tecnica', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pinturas', sa.Column('movimiento', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pinturas', type_='foreignkey')
    op.drop_constraint(None, 'pinturas', type_='foreignkey')
    op.drop_column('pinturas', 'movimiento_id')
    op.drop_column('pinturas', 'tecnica_id')
    # ### end Alembic commands ###
