# Generated by Django 5.0.7 on 2024-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('autor', models.CharField(default='Enrique Tábara', max_length=255)),
                ('dimensiones', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tecnica', models.CharField(max_length=255)),
                ('movimiento', models.CharField(max_length=255)),
                ('estado_conservacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('adicionales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
