# Generated by Django 5.0.7 on 2024-08-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obras/'),
        ),
    ]
