from .autor import autor
from .categoria import categoria
from .movimiento import movimiento
from .multimedia import multimedia
from .newsletter import newsletter
from .obra import obra
from .pintura import pintura
from .publicacion import publicacion
from .tecnica import tecnica
from .ubicacion import ubicacion
from .usuario import usuario
